dol_status_controller:
    path: /herald{tslash}
    defaults: { _controller: dol.status.main:handle_warmap, tslash: "/" }
    requirements:
        tslash: /?
dol_herald_ladder:
    path: /herald/{cmd}{tslash}
    defaults: { _controller: dol.status.main:handle_ladder, cmd: "", tslash: "/" }
    requirements:
        cmd: (active|players|guilds|kills|deathblow|solo|albion|midgard|hibernia)?
        tslash: /?
dol_herald_searchform:
    path: /herald/search{tslash}
    defaults: { _controller: dol.status.main:handle_searchform, tslash: "/" }
    requirements:
        tslash: /?
dol_herald_search:
    path: /herald/{cmd}/{params}{tslash}
    defaults: { _controller: dol.status.main:handle, cmd: "", params: "", tslash: "/" }
    requirements:
        cmd: (search|albion|midgard|hibernia)
        params: ([[:alnum:]À-ÿ ]+)
        tslash: /?
dol_herald_sheet:
    path: /herald/{cmd}/{params}{tslash}
    defaults: { _controller: dol.status.main:handle_sheet, cmd: "", params: "", tslash: "/" }
    requirements:
        cmd: (player|guild)
        params: ([[:alnum:]À-ÿ ]+)
        tslash: /?
dol_herald_images:
    path: /herald/{cmd}/{params}{tslash}
    defaults: { _controller: dol.status.images:handle, cmd: "", params: "", tslash: "/" }
    requirements:
        cmd: (banner|sigsmall|siglarge|sigdetailed)
        params: ([[:alnum:]À-ÿ ]+)?
        tslash: /?

dol_herald_badsearch:
    path: /herald/{notcmd}/{notparams}{tslash}
    defaults: { _controller: dol.status.main:handle_badsearch, cmd: "badsearch", params: "", tslash: "/", notcmd: "", notparams: "" }
    requirements:
        notcmd: (search)
        notparams: .*
        tslash: /?

dol_status_status:
    path: /status{tslash}
    defaults: { _controller: dol.status.status:handle, tslash: "/" }
    requirements:
        tslash: /?
dol_status_statusmini:
    path: /status/mini{tslash}
    defaults: { _controller: dol.status.status:handle_mini, tslash: "/" }
    requirements:
        tslash: /?
dol_status_statusrvr:
    path: /status/rvrmini{tslash}
    defaults: { _controller: dol.status.status:handle_rvrmini, tslash: "/" }
    requirements:
        tslash: /?


dol_status_game:
    path: /account
    defaults: { _controller: dol.status.game:handle }

dol_status_book:
    path: /grimoire
    defaults: { _controller: dol.status.main:handle_book }
