dol_status_controller:
    path: /herald/{cmd}/{params}{tslash}
    defaults: { _controller: dol.status.main:handle, cmd: "", params: "", tslash: "/" }
    requirements:
        cmd: (active|players|guilds|kills|deathblow|solo|player|guild|search|albion|midgard|hibernia|signature|banner|sigsmall|siglarge|sigdetailed)?
        params: ([[:alnum:]À-ÿ ]+)?
        tslash: /?
dol_status_badsearch:
    path: /herald/{notcmd}/{notparams}{tslash}
    defaults: { _controller: dol.status.main:handle, cmd: "badsearch", params: "", tslash: "/", notcmd: "", notparams: "" }
    requirements:
        notcmd: (search)
        notparams: .*
        tslash: /?

dol_status_images:
    path: /herald/{cmd}/{params}{tslash}
    defaults: { _controller: dol.status.images:handle, cmd: "", params: "", tslash: "/" }
    cmd: (banner|sigsmall|siglarge|sigdetailed)
    params: ([[:alnum:]À-ÿ ]+)?
    tslash: /?

dol_status_game:
    path: /game
    defaults: { _controller: dol.status.main:handle_game }

dol_status_book:
    path: /grimoire
    defaults: { _controller: dol.status.main:handle_book }

dol_status_status:
    path: /status/{type}{tslash}
    defaults: { _controller: dol.status.main:handle_status, type: "all", tslash: "/" }
    requirements:
        type: (mini|rvrmini)?
        tslash: /?
