services:
    dol.status.main:
        class: dol\status\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - %core.root_path%
            - .%core.php_ext%
            - '@dol.status.controller_helper'

    dol.status.controller_helper:
        class: dol\status\controller\helper
        arguments:
            - '@template'
            - '@cache.driver'
            - '@config'
            - %core.root_path%
          
    dol.status.listener:
        class: dol\status\event\listener
        arguments:
            - @dol.status.main
            - @auth
            - @config
            - @controller.helper
            - @path_helper
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }