services:
    dol.status.main:
        class: dol\status\controller\main
        arguments:
            - %core.root_path%
            - .%core.php_ext%
            
    acme.demo.listener:
        class: dol\status\event\listener
        tags:
            - { name: event.listener }
